version: '3'

services:
  node:
    build:
      context: .
    volumes:
      - static:/usr/src/app/build:rw
      - storybook:/usr/src/app/storybook-static:rw
      - yarn:/root/.yarn
    environment:
      PORT: 4000
      NODE_ENV: production
    restart: unless-stopped

  nginx:
    build:
      context: ./nginx
    volumes:
      - static:/data/static:ro
      - storybook:/data/storybook:ro
    ports:
      - "8080:80"
    environment:
      - NGINX_HOST=island.reonclud.com
      - NGINX_PORT=80
    restart: unless-stopped

  # cypress:
  #   image: "cypress/included:3.2.0"
  #   depends_on:
  #     - node
  #     - nginx
  #   environment:
  #     - CYPRESS_baseUrl=http://nginx
  #   working_dir: /e2e
  #   volumes:
  #     - ./:/e2e

volumes:
  static:
  storybook:
  yarn:
