export enum IconName {
  Add = "add",
  ArrowRight = "arrowRight",
  ArrowLeft = "arrowLeft",
  Back = "back",
  Calendar = "calendar",
  Check = "check",
  Close = "close",
  Dots = "dots",
  Drop = "drop",
  Edit = "edit",
  Lock = "lock",
  Reload = "reload",
  Search = "search",
  Trash = "trash",
  Upload = "upload",
  User = "user",
  Hamburger = "hamburger",
  Graph = "graph",
  Law = "law",
  Plane = "plane",
  Wallet = "wallet",
  Wheelchair = "wheelchair",
  Phone = "phone",
  Att = "att",
  Facebook = "facebook",
  IndicatorDown = "indicatorDown",
}
